name: "Mxbc"

on:
  push:
    branches:
      - main
  schedule:   
    - cron: '0 9 * * *'   # 定时运行的时间，国际标准时间，北京时间要+8
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: install packages 
        run: npm install
      - name: run sign
        run: node ./mxbc.js
