name: 京东华硕爱奇艺

on:
    workflow_dispatch:
    schedule:
        - cron: "24 4,10,16 * * *"
    watch:
        types: [started]
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【京东华硕爱奇艺】"
              run: |
                  node mxbc.js
