name: "Mxbc"

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: install packages 
        run: npm install axios
             npm install request
             npm install jsrsasign
      - name: run sign
        run: node mxbc.js
      - uses: actions/upload-artifact@v2
        with:
          name: mxbc-log
          path: log/mihoyo.log
