name: 蜜雪冰城签到

on:
    workflow_dispatch:
    schedule:
        - cron: "0 22 * * *"
    watch:
        types: [started]
jobs:
    build:
        env:
           mxbchd: ${{ secrets.mxbchd }}
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码和Node环境
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install axios 
                  npm install request 
                  npm install jsrsasign
            - name: "运行【蜜雪冰城签到】"
              run: |
                  node mxbc.js
