name: "Mxbc SignIn"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: install packages 
        run: npm install jsrsasign
      - name: run sign
        run: node ./mxbc.js
