name: xhu

on:
  workflow_dispatch:
  schedule:
     - cron: "0,30 * * * *" 
    # 0 22 * * *

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Set up Python 3.7
              uses: actions/setup-python@v1
              with:
                   python-version: 3.7
            - name: 安装依赖包
              run: |
                  python -m pip install --upgrade pip
                  pip install requests
                  pip install lxml
            - name: "运行【西华】"
              run: |
                  python3 xhu.py
              env:
                  Wxpusher_Token: ${{ secrets.Wxpusher_Token }}
