name: 雨云

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *" 
    # 0 22 * * *

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                   python-version: 3.9.12
            - name: 安装依赖包
              run: |
                  python -m pip install --upgrade pip
                  pip install requests
            - name: "运行【云雨】"
              env:
                  DD_BOT_ACCESS_TOKEN: ${{ secrets.DD_BOT_ACCESS_TOKEN }}
              run: |
                  python3 yuyun.py
